Instance: NationalDirectoryCapabilityStatement
InstanceOf: CapabilityStatement
Title: "vhdir.meteorapp.com/metadata"
Description: "National Directory - Capability Statement"

Usage: #definition
* url = "https://vhdir.meteorapp.com/baseR4"
* name = "NationalCareDirectory"
* version = "0.1.0"
* status = #draft
* experimental = true
* publisher = "MITRE, Inc"
* kind = #capability
* date = "2022-05-03T03:25:00.108Z"
* software.version = "6.1.0"
* software.name = "Vault Server"
* software.releaseDate = "2022-05-03T03:25:00.108Z"
* fhirVersion = #4.0.1
* format = #json
* rest.mode = #server
* rest.resource[0].type = #AuditEvent
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].versioning = #no-version
* rest.resource[+].type = #Bundle
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #no-version
* rest.resource[+].type = #CareTeam
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #CodeSystem
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #Communication
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #CommunicationRequest
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].versioning = #no-version
* rest.resource[+].type = #Endpoint
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #HealthcareService
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #InsurancePlan
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #Location
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #Organization
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #OrganizationAffiliation
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #Practitioner
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #PractitionerRole
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #Provenance
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].versioning = #no-version
* rest.resource[+].type = #SearchParameter
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #Task
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #StructureDefinition
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.resource[+].type = #Subscription
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].versioning = #no-version
* rest.resource[+].type = #ValueSet
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #no-version
* rest.resource[+].type = #VerificationResult
* rest.resource[=].interaction[0].code = #read
* rest.resource[=].interaction[+].code = #create
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].versioning = #versioned
* rest.security.service[0] = http://terminology.hl7.org/CodeSystem/restful-security-service#SMART-on-FHIR
* rest.security.service[=].text = "OAuth2 using SMART-on-FHIR profile (see http://docs.smarthealthit.org)"
* rest.security.service[+] = http://fhir.udap.org/CodeSystem/capability-rest-security-service#UDAP
* rest.security.service[=].text = "OAuth 2 using UDAP profile (see http://www.udap.org)"
* rest.security.extension.extension[0].url = "token"
* rest.security.extension.extension[=].valueUri = "https://vhdir.meteorapp.com/oauth/token"
* rest.security.extension.extension[+].url = "authorize"
* rest.security.extension.extension[=].valueUri = "https://vhdir.meteorapp.com/oauth/authorize"
* rest.security.extension.extension[+].url = "register"
* rest.security.extension.extension[=].valueUri = "https://vhdir.meteorapp.com/oauth/registration"
* rest.security.extension.extension[+].url = "manage"
* rest.security.extension.extension[=].valueUri = "https://vhdir.meteorapp.com/authorizations/manage"
* rest.security.extension.extension[+].url = "introspect"
* rest.security.extension.extension[=].valueUri = "https://vhdir.meteorapp.com/authorizations/introspect"
* rest.security.extension.extension[+].url = "revoke"
* rest.security.extension.extension[=].valueUri = "https://vhdir.meteorapp.com/authorizations/revoke"
* rest.security.extension.url = "http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris"